In [6]:
import numpy as np
array_two = np.arange(1,4) ** 2
array_three = np.arange(1 , 4) ** 3
print(array_two + array_three)

[ 2 12 36]


In [8]:
sample_array = np.array([1,2,3])

In [9]:
print(np.power(sample_array, 4))

[ 1 16 81]


In [10]:
print(np.negative(sample_array))

[-1 -2 -3]


In [11]:
np.exp(sample_array) # e^1 e^2 e^3

array([ 2.71828183,  7.3890561 , 20.08553692])

In [12]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229])

In [13]:
np.sin(sample_array)

array([0.84147098, 0.90929743, 0.14112001])

# N Dimentional array

In [18]:
import numpy as np
x = np.arange(3)
y = np.arange(3)
z = np.arange(3)
multi_array =np.array([y,z])
print(multi_array)
print(multi_array.shape)

[[0 1 2]
 [0 1 2]]
(2, 3)


In [37]:
# 50 numbers between 1 to 10
w= np.linspace(1,10,50)
print(w)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


# Slicing one dimentional array

In [29]:
# Slicing
import numpy as np
x = np.arange(1,10)
print(x)
print(x[2:7])
print(x[:7])
print(x[2:])

[1 2 3 4 5 6 7 8 9]
[3 4 5 6 7]
[1 2 3 4 5 6 7]
[3 4 5 6 7 8 9]


# Multi Dimentional arrays

In [36]:
import numpy as np
x= np.arange(9)
print(x)
x=np.arange(9).reshape(3,3)
print(x)

# number of columns will be automatically determined
x=np.arange(9).reshape(3,-1)
print(x)

# 2 3x3
x=np.arange(18).reshape(2,3,3)
print(x)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


# Slicing multi dimentional array

In [62]:
import numpy as np
y=np.arange(9).reshape(3,3)
print(y)
print('----------')
print(x[2,1])
print('----------')
x=np.arange(18).reshape(3,2,3)
print(x)
print('----------')
print(x[1, 1, 1])
print('----------')
print(x[1, 0:2, 1])
print('----------')
print(x[1,0:2, 0:3])
print('----------')
print(x[1, :, :])
print('----------')
# exactly as above
print(x[1, ...])
print('----------')
print(x[:, 0, 0])
print('----------')
# every second element of each row (:2 is step)
print(x[1, :2, :3:2])
print('----------')
comparison_operation = x > 5
print(comparison_operation)
print('----------')
comparison_operation = x > 5
print(x[comparison_operation])
print('----------')
print(x[x > 5])
print('----------')


[[0 1 2]
 [3 4 5]
 [6 7 8]]
----------
[15 16 17]
----------
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]
----------
10
----------
[ 7 10]
----------
[[ 6  7  8]
 [ 9 10 11]]
----------
[[ 6  7  8]
 [ 9 10 11]]
----------
[[ 6  7  8]
 [ 9 10 11]]
----------
[ 0  6 12]
----------
[[ 6  8]
 [ 9 11]]
----------
[[[False False False]
  [False False False]]

 [[ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]]]
----------
[ 6  7  8  9 10 11 12 13 14 15 16 17]
----------
[ 6  7  8  9 10 11 12 13 14 15 16 17]


# Manipulating Array Shapes

In [81]:
import numpy as np
x=np.arange(9).reshape(3,3)
print(x)
print('----------')
ravelled_array = x.ravel()
print(ravelled_array)
print('----------')
flattened_array = x.flatten()
print(flattened_array)
# flatten always return a copy but ravel return a view of the original array
# if you change the ravelled in above the actual array gets changed as well
print('----------')

y = np.arange(9)
y.shape = [3,3]
print(y)
print('----------')

print(y.transpose())
print('----------')
print(y.T) # rthe same effect
print('----------')

print(np.resize(y, (6,6))) # data gets repeated
print('----------')

print(np.zeros((6,))) # one dimentional
print('----------')

print(np.zeros((6,), dtype = int)) # one dimentional
print('----------')

print(np.zeros((3,2), dtype = int)) 
print('----------')

print(np.ones((3,2), dtype = int)) 
print('----------')

print(np.eye(3)) 
print('----------')

print(np.random.rand(4,4)) # uniform distribution from zero and one
print('----------')

[[0 1 2]
 [3 4 5]
 [6 7 8]]
----------
[0 1 2 3 4 5 6 7 8]
----------
[0 1 2 3 4 5 6 7 8]
----------
[[0 1 2]
 [3 4 5]
 [6 7 8]]
----------
[[0 3 6]
 [1 4 7]
 [2 5 8]]
----------
[[0 3 6]
 [1 4 7]
 [2 5 8]]
----------
[[0 1 2 3 4 5]
 [6 7 8 0 1 2]
 [3 4 5 6 7 8]
 [0 1 2 3 4 5]
 [6 7 8 0 1 2]
 [3 4 5 6 7 8]]
----------
[0. 0. 0. 0. 0. 0.]
----------
[0 0 0 0 0 0]
----------
[[0 0]
 [0 0]
 [0 0]]
----------
[[1 1]
 [1 1]
 [1 1]]
----------
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
----------
[[0.31160269 0.78416347 0.59006876 0.46814765]
 [0.80003567 0.6814685  0.34219447 0.93238281]
 [0.5621633  0.70706515 0.12872624 0.57109158]
 [0.67401957 0.22942786 0.77083178 0.04247031]]
----------


# Matrix Multiplication

In [88]:
import numpy as np
mat_a= np.matrix([0,3,5,5,5,2]).reshape(2,3)
print(mat_a)
print('----------')
import numpy as np
mat_b= np.matrix([3,4,3,-2,4,-2]).reshape(3,2)
print(mat_b)
print('----------')

print(mat_a * mat_b)
print('----------')

product = np.matmul(mat_a, mat_b)
print(product)
print('----------')

#you can use the numpy array as well
mat_a= np.array([0,3,5,5,5,2]).reshape(2,3)
mat_b= np.array([3,4,3,-2,4,-2]).reshape(3,2)
product = np.matmul(mat_a, mat_b)
print(product)
print('----------')

print(mat_a @ mat_b)
print('----------')


[[0 3 5]
 [5 5 2]]
----------
[[ 3  4]
 [ 3 -2]
 [ 4 -2]]
----------
[[ 29 -16]
 [ 38   6]]
----------
[[ 29 -16]
 [ 38   6]]
----------
[[ 29 -16]
 [ 38   6]]
----------
[[ 29 -16]
 [ 38   6]]
----------


# Stacking

In [113]:
import numpy as np
x=np.arange(4).reshape(2,2)
print(x)
print('----------')

y=np.arange(4, 8).reshape(2,2) # fom 4 to 7
print(y)
print('----------')

z= np.hstack((x,y))
print(z)
print('----------')

x=np.arange(4).reshape(2,2)
print(x)
y = np.arange(8).reshape(4,2)
print(y)
z = np.vstack((x,y))
print(z)
print('----------')

w= np.concatenate((x,y), axis=0)
print(w)
print('----------')

# for along the axis=1 you need to have them the same in row
x=np.arange(4).reshape(2,2)
print(x)
y = np.arange(8).reshape(2,4)
print(y)
z = np.concatenate((x,y), axis=1)
print(z)
# horizonat stacking is the same a concatenate around 1 axis
print('----------')

# depth stacking
x=np.arange(4).reshape(2,2)
y = x * 2
depth_stack = np.dstack((x,y))
print(x)
print(y)
print(depth_stack) # now it has 2 in depth
print(depth_stack.shape)
print('----------')

x=np.arange(4).reshape(2,2,1)
y = x * 2
depth_stack = np.dstack((x,y))
print(x)
print(y)
print(depth_stack) # now it has 2 in depth
print(depth_stack.shape)
print('----------')

# column stacking is the same as horizontal stacking
x=np.arange(4).reshape(2,2)
print(x)
y = x * 2
print(y)
print(np.column_stack((x,y)))
print(np.column_stack((x,y)) == np.hstack((x,y)))
print('----------')


# row stacking is the same as vertical stacking
x=np.arange(4).reshape(2,2)
print(x)
y = x * 2
print(y)
print(np.row_stack((x,y)))
print(np.row_stack((x,y)) == np.vstack((x,y)))
print('----------')

[[0 1]
 [2 3]]
----------
[[4 5]
 [6 7]]
----------
[[0 1 4 5]
 [2 3 6 7]]
----------
[[0 1]
 [2 3]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0 1]
 [2 3]
 [0 1]
 [2 3]
 [4 5]
 [6 7]]
----------
[[0 1]
 [2 3]
 [0 1]
 [2 3]
 [4 5]
 [6 7]]
----------
[[0 1]
 [2 3]]
[[0 1 2 3]
 [4 5 6 7]]
[[0 1 0 1 2 3]
 [2 3 4 5 6 7]]
----------
[[0 1]
 [2 3]]
[[0 2]
 [4 6]]
[[[0 0]
  [1 2]]

 [[2 4]
  [3 6]]]
(2, 2, 2)
----------
[[[0]
  [1]]

 [[2]
  [3]]]
[[[0]
  [2]]

 [[4]
  [6]]]
[[[0 0]
  [1 2]]

 [[2 4]
  [3 6]]]
(2, 2, 2)
----------
[[0 1]
 [2 3]]
[[0 2]
 [4 6]]
[[0 1 0 2]
 [2 3 4 6]]
[[ True  True  True  True]
 [ True  True  True  True]]
----------
[[0 1]
 [2 3]]
[[0 2]
 [4 6]]
[[0 1]
 [2 3]
 [0 2]
 [4 6]]
[[ True  True]
 [ True  True]
 [ True  True]
 [ True  True]]
----------
